pipeline {
    agent any
    stages {
        stage('Run') {
            steps {
                printf """TituloPelicula=Avatar\n
CantidadEspectadores=50000\n
CantidadSalas=5000\n
GananciaBruta=250000000\n
GananciaNeta=2.0E8"""
                printf """TituloPelicula=Avengers: Endgame\n
CantidadEspectadores=45000\n
CantidadSalas=4500\n
GananciaBruta=202500000\n
GananciaNeta=1.62E8"""
                printf """TituloPelicula=Avatar: The Way of Water\n
CantidadEspectadores=40000\n
CantidadSalas=4000\n
GananciaBruta=160000000\n
GananciaNeta=1.28E8"""
                printf """TituloPelicula=Titanic\n
CantidadEspectadores=35000\n
CantidadSalas=3500\n
GananciaBruta=122500000\n
GananciaNeta=9.8E7"""
                printf """TituloPelicula=Star Wars: Episode VII - The Force Awakens\n
CantidadEspectadores=30000\n
CantidadSalas=3000\n
GananciaBruta=90000000\n
GananciaNeta=7.2E7"""
                printf """TituloPelicula=Avengers: Infinity War\n
CantidadEspectadores=25000\n
CantidadSalas=2500\n
GananciaBruta=62500000\n
GananciaNeta=5.0E7"""
                printf """TituloPelicula=Spider-Man: No Way Home\n
CantidadEspectadores=20000\n
CantidadSalas=2000\n
GananciaBruta=40000000\n
GananciaNeta=3.2E7"""
                printf """TituloPelicula=Jurassic World\n
CantidadEspectadores=15000\n
CantidadSalas=1500\n
GananciaBruta=22500000\n
GananciaNeta=1.8E7"""
                printf """TituloPelicula=The Lion King\n
CantidadEspectadores=10000\n
CantidadSalas=1000\n
GananciaBruta=10000000\n
GananciaNeta=8000000.0"""
                printf """TituloPelicula=The Avengers\n
CantidadEspectadores=5000\n
CantidadSalas=500\n
GananciaBruta=2500000\n
GananciaNeta=2000000.0"""
            }
        }
    }
}
