pipeline {
    agent any

    stages {
        stage('Run') {
            steps {
                    dir('/var/jenkins_home/workspace/ejercicio Usuario jenkins/curso_de_java') {
                        readFile './empleados.txt'
                    }
            }
        }
    }
}